<?xml version ="1.0"?> 
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name = "wheel_radius" value = "0.1"/>
    <xacro:property name = "wheel_length" value = "0.04"/>
    <xacro:property name = "wheel_height" value = "0.064"/>

    <xacro:include filename="common_properties.xacro"/>

    <link name="base_footprint"/>

    <link name="base_robot">
        <visual>
            <origin xyz="0 0 0" rpy = "0 0 ${pi/2}"/>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/robot_base.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="grey"/>
        </visual>
    </link>

    <joint name="base_to_footprint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_robot"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="upper_body">
        <visual>
            <origin xyz="0 0 0" rpy ="0 0 0.5216"/>
            <geometry>
                <mesh filename="package://my_robot_description/meshes/upper_body.stl" scale="0.001 0.001 0.001"/>
            </geometry>
        </visual>
    </link>

    <joint name="upper_body_to_base_joint" type="revolute">
        <parent link="base_robot"/>
        <child link="upper_body"/>
        <origin xyz="0 0 0.85" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-3*pi/8}" upper="${3*pi/8}" effort="100" velocity="1"/>
    </joint>

    <xacro:macro name="wheel_link" params="prefix rpy">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${rpy}"/>
                <material name="black"/>
            </visual>
        </link>
    </xacro:macro>
    <xacro:wheel_link prefix="front" rpy="${pi / 2.0} 0 ${pi / 2.0}"/>
    <xacro:wheel_link prefix="left" rpy="${pi / 2.0} 0 ${pi / 6.0}"/>
    <xacro:wheel_link prefix="right" rpy="${pi / 2.0} 0 ${-pi / 6.0}"/>

    <xacro:macro name="wheel_joint" params="prefix origin_x origin_y axis">
        <joint name="base_${prefix}_wheel_joint" type="continuous">
            <parent link="base_robot"/>
            <child link="${prefix}_wheel_link"/>
            <axis xyz="${axis}"/>
            <origin xyz="${origin_x} ${origin_y} ${wheel_height}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>
    <xacro:wheel_joint prefix="front" origin_x="${wheel_length/2.0+0.279}" 
                       origin_y="0" axis="1 0 0"/>
    <xacro:wheel_joint prefix="left" origin_x="${-0.127-(wheel_length/2.0)*sin(pi/3)}" 
                       origin_y="${0.235+(wheel_length/2.0)*cos(pi/3)}"
                       axis="${-sin(pi/6)} ${cos(pi/6)} 0"/>
    <xacro:wheel_joint prefix="right" origin_x="${-0.127-(wheel_length/2.0)*sin(pi/3)}" 
                       origin_y="${-0.235-(wheel_length/2.0)*cos(pi/3)}" 
                       axis="${sin(pi/6)} ${cos(pi/6)} 0"/>
    
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>
    <joint name="lidar_to_upper_body_joint" type="fixed">
        <parent link="upper_body"/>
        <child link="lidar"/>
        <origin xyz="0 0 0.265" roy="0 0 0"/>
    </joint>
</robot>
